const NOTE_NAMES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const PC={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11};
const QUALITIES={m:[0,3,7],min:[0,3,7],maj:[0,4,7],'' :[0,4,7],dim:[0,3,6],aug:[0,4,8]};
const styleAdd={worship:['maj9','m9','13'],gospel:['maj9','m9','13','7'],rnb:['maj9','m9','13','7'],jazz:['maj9','m9','13','7','7b9'],rich:['maj9','m9','13','7']};
const app={progression:document.getElementById('progression'),style:document.getElementById('style'),level:document.getElementById('level'),result:document.getElementById('result'),selectedName:document.getElementById('selectedName'),notes:document.getElementById('notes'),left:document.getElementById('leftHand'),right:document.getElementById('rightHand'),keyboard:document.getElementById('keyboard'),saved:document.getElementById('saved'),resultTitle:document.getElementById('resultTitle')};
let current=[];let selected=0;
function parseChord(s){s=s.trim();const m=s.match(/^([A-Ga-g])([#b]?)(.*)$/);if(!m)return null;const root=(m[1].toUpperCase()+m[2]);if(PC[root]===undefined)return null;let q=m[3].trim();if(q==='maj7')q='maj';return {root,pc:PC[root],quality:q};}
function rootTriad(c){const q=c.quality.startsWith('m')?'m':c.quality==='dim'?'dim':c.quality==='aug'?'aug':'';return QUALITIES[q]||QUALITIES[''];}
function noteName(pc){return NOTE_NAMES[(pc+120)%12]}
function buildChord(c,name){const ints=name==='maj9'?[0,4,7,11,14]:name==='m9'?[0,3,7,10,14]:name==='13'?[0,4,7,10,14,21]:name==='7'?[0,4,7,10]:name==='7b9'?[0,4,7,10,13]:rootTriad(c);return ints.map(i=>({pc:(c.pc+i)%12,oct:3+Math.floor(i/12),name:noteName(c.pc+i)}));}
function chooseName(c,index){const names=styleAdd[app.style.value]||styleAdd.gospel;let n=names[index%names.length];if(c.quality.startsWith('m'))n=n==='maj9'?'m9':n;if(c.quality==='dim')return 'dim';return n;}
function passing(a,b){const delta=(b.pc-a.pc+12)%12;if(delta===2)return 'A13';if(delta===5)return 'D7';if(delta===7)return 'A7';if(delta===10)return 'C#7';return null;}
function generate(){const raw=app.progression.value.split(/[ ,→-]+/).map(x=>x.trim()).filter(Boolean);const parsed=raw.map(parseChord);if(!raw.length||parsed.some(x=>!x)){app.result.innerHTML='<div class="hint">Enter chords like G, C, D, G. Supported roots: A–G with # or b.</div>';return}current=parsed.map((c,i)=>({base:raw[i],chord:c,name:chooseName(c,i)}));selected=0;renderResult();renderSelected();}
function renderResult(){const styleName=app.style.options[app.style.selectedIndex].text;app.resultTitle.textContent=`${styleName} · ${app.level.options[app.level.selectedIndex].text}`;const row=document.createElement('div');row.className='progression-row';current.forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.className='chord-chip';b.textContent=x.chord.root+x.name;b.onclick=()=>{selected=i;renderSelected()};row.appendChild(b);if(i<current.length-1){const p=passing(x.chord,current[i+1].chord);if(p){const s=document.createElement('span');s.className='passing';s.textContent=' + '+p+' ';row.appendChild(s)}const a=document.createElement('span');a.className='arrow';a.textContent='→';row.appendChild(a)}});app.result.innerHTML='';app.result.appendChild(row);const tip=document.createElement('div');tip.className='hint';tip.textContent='Tap a chord to see its exact notes. Passing chords are shown in purple.';app.result.appendChild(tip);}
function renderSelected(){const x=current[selected];if(!x)return;const ns=buildChord(x.chord,x.name);app.selectedName.textContent=x.chord.root+x.name;app.notes.innerHTML='';ns.forEach(n=>{const e=document.createElement('span');e.className='note';e.textContent=n.name+ n.oct;app.notes.appendChild(e)});const left=ns.slice(0,1).map(n=>n.name+'2');const right=ns.slice(1).map(n=>n.name+'3');app.left.textContent=left.join(' ')||'—';app.right.textContent=right.join(' ')||'—';drawKeyboard(ns);}
function drawKeyboard(ns){app.keyboard.innerHTML='';const active=new Set(ns.map(n=>n.pc));for(let pc=48;pc<=72;pc++){const name=noteName(pc);const isBlack=[1,3,6,8,10].includes(pc%12);if(isBlack)continue;const w=document.createElement('div');w.className='white'+(active.has(pc%12)?' active':'');w.dataset.pc=pc%12;const span=document.createElement('span');span.textContent=name;w.appendChild(span);app.keyboard.appendChild(w)}const whites=[48,50,52,53,55,57,59,60,62,64,65,67,69,71];whites.forEach((p,i)=>{const blackPc=p+([0,2,5,7,9].includes(p%12)?1:0);if(![1,3,6,8,10].includes(blackPc%12))return;const b=document.createElement('div');b.className='black'+(active.has(blackPc%12)?' active':'');b.style.left=(i*38+25)+'px';app.keyboard.appendChild(b)});}
function save(){const value=app.progression.value.trim();if(!value)return;const arr=JSON.parse(localStorage.getItem('chordpilot_saved')||'[]');if(!arr.includes(value))arr.unshift(value);localStorage.setItem('chordpilot_saved',JSON.stringify(arr.slice(0,20)));renderSaved();}
function renderSaved(){const arr=JSON.parse(localStorage.getItem('chordpilot_saved')||'[]');app.saved.innerHTML='';if(!arr.length){app.saved.innerHTML='<div class="hint">Nothing saved yet.</div>';return}arr.forEach((v,i)=>{const d=document.createElement('div');d.className='saved-item';const t=document.createElement('span');t.textContent=v;const b=document.createElement('button');b.type='button';b.textContent='Load';b.onclick=()=>{app.progression.value=v;generate()};d.append(t,b);app.saved.appendChild(d)})}
async function play(){const x=current[selected];if(!x)return;const ns=buildChord(x.chord,x.name);const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C();const now=ctx.currentTime;ns.forEach((n,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=440*Math.pow(2,((n.pc+12*(n.oct-4))-9)/12);g.gain.setValueAtTime(0.0001,now);g.gain.exponentialRampToValueAtTime(0.13,now+0.03+i*.02);g.gain.exponentialRampToValueAtTime(0.0001,now+1.6);o.connect(g).connect(ctx.destination);o.start(now);o.stop(now+1.7)});}
document.getElementById('generateBtn').onclick=generate;document.getElementById('saveBtn').onclick=save;document.getElementById('playBtn').onclick=play;document.getElementById('style').onchange=generate;document.getElementById('level').onchange=generate;document.getElementById('clearSavedBtn').onclick=()=>{localStorage.removeItem('chordpilot_saved');renderSaved()};renderSaved();generate();
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;document.getElementById('installBtn').classList.remove('hidden')});document.getElementById('installBtn').onclick=async()=>{if(!deferred)return;deferred.prompt();deferred=null};if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
